fix(zsh): error on `/bin/startx` absence; potential error on systems without `systemd` (`$XDG_VTNR`); chance of running `startx` on `tty`'s other than `/dev/tty1`

diff --git a/zsh/.config/zsh/zshrc b/zsh/.config/zsh/zshrc
--- a/zsh/.config/zsh/zshrc
+++ b/zsh/.config/zsh/zshrc
@@ -28,8 +28,40 @@ zmodload zsh/zprof
 
 ### Start X on login
 
-# Only start if DISPLAY == "" && XDG_VTNR == 1
-[[ -z $DISPLAY && $XDG_VTNR -eq 1 && -x startx ]] && exec startx > /dev/null 2>&1
+maybe_startx () {
+
+  # Continue to the terminal if in the pseudo terminal, not TTY
+  tty | grep -q '^/dev/pts' && return
+
+  echo "Starting X server...";
+
+  # Trow to shell if not on first TTY
+  if [ ! "$(tty)" = '/dev/tty1' ]; then
+    echo "ERROR: You are not in the first TTY. X server won't start."
+    echo "Leaving you in the shell."
+    return;
+  fi
+
+  # Throw to shell if `DISPLAY` is already set
+  if ! [ -z $DISPLAY ]; then
+    echo "ERROR: \`DISPLAY\` is already set. X server already running on this TTY and you seeng this message. Something wrong."
+    echo "Leaving you in the shell."
+    return
+  fi
+
+  # Throw to shell if `startx` is missing
+  if [ ! -x /bin/startx ]; then
+    echo "ERROR: Seems like the X server is not installed or not properly installed: \`startx\` is not in your \`PATH\`. X server won't start."
+    echo "Leaving you in the shell."
+    return
+  fi
+
+  exec startx >> $HOME/.local/share/xinitrc/xinitrc.log 2>> $HOME/.local/share/xinitrc/xinitrc.error.log
+}
+
+# Only start if `DISPLAY == "" && startx`
+maybe_startx
+
 
 # FZF
 #source /usr/share/fzf/key-bindings.zsh
