feat(bin): now defaults to such locations (descending priority): `$HOME/Pictures/pepes` -> `$XDG_PICTURES_DIR/pepes` -> `$XDG_DATA_HOME/peepos_location` -> `$1`

diff --git a/bin/.local/bin/random-pepe b/bin/.local/bin/random-pepe
--- a/bin/.local/bin/random-pepe
+++ b/bin/.local/bin/random-pepe
@@ -1,25 +1,41 @@
 #!/bin/sh
 
 # Characters to be used in PEEPO...
-chars='     /********,.@@@%'
+# chars='     /********,.@@@%'
+# chars='     /********,%#@&!!@#$%^&).@@@%'
 
-pepes_dir="${1:-"$HOME/Pictures/pepes"}"
+[ -f "${XDG_CONFIG_HOME}/user-dirs.dirs" ] && . "${XDG_CONFIG_HOME}/user-dirs.dirs"
+
+# Subsequent defaults
+# Ascending priority
+pepes_dir="${HOME}/Pictures/pepes"
+
+[ -n "${XDG_PICTURES_DIR}" ] && pepes_dir="${XDG_PICTURES_DIR}/pepes"
+[ -s "${XDG_DATA_HOME}/peepos_location" ] && pepes_dir=$(envsubst < "${XDG_DATA_HOME}/peepos_location")
+[ -n "${1}" ] && pepes_dir="${1}"
 
 # Exit if there is no place of peepos...
-if [ ! -d "$pepes_dir" ]; then
+if [ ! -d "${pepes_dir}" ]; then
   echo 'Nowhere to find peepos...'
+  echo "random-pepe: error: no pepes in ${pepes_dir}" >&2
   exit 1
 fi
 
-peepos=$(find "$pepes_dir" -type f -iname "*.png" -o -type f -iname "*.jpg" -o -type f -iname "*.webp")
+# Retreive peepos...
+peepos=$(find "${pepes_dir}" -type f -iname "*.png" -o -type f -iname "*.jpg" -o -type f -iname "*.webp")
 
 # Exit if there is not a single peepo...
-if [ "$(wc -l "$peepos")" = 0 ]; then
-  echo 'No peepos...'
+if [ "$(wc -l "${peepos}")" = 0 ]; then
+  echo 'No peepos there...'
   exit 1
 fi
 
-# Get random peepo...
-peepo=$(echo "$peepos" | shuf -n 1)
+# Select random peepo...
+peepo=$(echo "${peepos}" | shuf -n 1)
 
-jp2a --colors --chars="$chars" --height=33 --width=85 "$peepo"
+# Debug stuff...
+echo "random-pepe: info: used image: ${peepo}" >&2
+
+# Convert peepo...
+#--chars="${chars}"
+jp2a --colors "${peepo}"
